title: Cognitive Services Lab
remote_theme: benc-uk/theme-msdark
buttons:
  - button2:
    text: Home
    href: /serverless-cosmos-lab
  - button2:
    text: Full Guide
    href: /serverless-cosmos-lab/guide
